name: edgex-ekuiper
version: git
license: Apache-2.0
summary: EdgeX eKuiper
description: |
  eKuiper is a lightweight IoT edge analytics software.

  This is a snap packaging of eKuiper tailored to the EdgeX Foundry snap,
  available at: https://snapcraft.io/edgexfoundry

  The snap is designed to work with EdgeX and is not supported 
  for standalone use.

  The snap is **NOT SUPPORTED** by the eKuiper community.
  For any EdgeX-related issues, please refer to:
  https://github.com/canonical/edgex-ekuiper-snap

  eKuiper source code: https://github.com/lf-edge/ekuiper

  eKuiper is a trademark of LF Projects: https://lfprojects.org

base: core20

architectures:
  - build-on: amd64
  - build-on: arm64

grade: stable
confinement: strict

epoch: 0

slots:
  edgex-secretstore-token:
    interface: content
    source:
      write: 
        - $SNAP_DATA/edgex-ekuiper

plugs:
  ekuiper-data:
    interface: content
    target: $SNAP_DATA

apps:
  kuiper:
    command: bin/kuiperd
    command-chain:
      - bin/source-env-file.sh
      - bin/setup-redis-credentials.sh
    daemon: simple
    environment:
      KuiperBaseKey: $SNAP_DATA
      VAULT_TOKEN_FILE: $SNAP_DATA/edgex-ekuiper/secrets-token.json
      SOURCE_FILE: $SNAP_DATA/etc/sources/edgex.yaml 
      CONNECTION_FILE: $SNAP_DATA/etc/connections/connection.yaml
    install-mode: disable
    restart-delay: 3s
    plugs: [network, network-bind]

  kuiper-cli:
    command: bin/kuiper
    environment:
      KuiperBaseKey: $SNAP_DATA
    plugs: [home, network, network-bind]

parts:
  helper-go:
    source: snap/local/helper-go
    plugin: make
    build-snaps:
      - go/1.18/stable
    override-build: |
      cd $SNAPCRAFT_PART_SRC
      make build
      install -DT ./helper-go $SNAPCRAFT_PART_INSTALL/bin/helper-go

  runtime-helpers:
    plugin: dump
    source: snap/local/runtime-helpers
    stage-packages:
      - curl
    stage-snaps:
      - yq/v4/stable

  kuiper:
    source: https://github.com/lf-edge/ekuiper.git
    source-tag: 1.7.3
    source-depth: 1
    plugin: make
    build-packages: [gcc, git, libczmq-dev, pkg-config, zip]
    stage-packages: [libzmq5]
    build-snaps:
      - go/1.18/stable
    override-build: |
      cd $SNAPCRAFT_PART_SRC
      
      export BUILD_PATH=$SNAPCRAFT_PART_BUILD
      make build_with_edgex
  
      find $SNAPCRAFT_PART_BUILD/kuiper-* -maxdepth 1 -mindepth 1 -exec cp -r '{}' $SNAPCRAFT_PART_INSTALL/ \;

      install "$SNAPCRAFT_PROJECT_DIR/etc/kuiper.yaml" "$SNAPCRAFT_PART_INSTALL/etc"
      install "$SNAPCRAFT_PROJECT_DIR/etc/edgex.yaml" "$SNAPCRAFT_PART_INSTALL/etc/sources"
      install "$SNAPCRAFT_PROJECT_DIR/etc/connection.yaml" "$SNAPCRAFT_PART_INSTALL/etc/connections"

      install -DT "$SNAPCRAFT_PART_SRC/LICENSE" "$SNAPCRAFT_PART_INSTALL/usr/share/doc/kuiper/LICENSE"
    stage:
      - -etc/ldap/
      - -etc/mgmt/

  local-bin:
    plugin: dump
    source: snap/local/bin
    organize:
      source-env-file.sh: bin/source-env-file.sh
