name: Tag & Release

on: 
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Git Tag Name (format: X.Y.Z-snap.N)' 
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Validate version
        run: |
          if [[ ! "${{ github.event.inputs.tag_name }}" =~ ^[0-9].[0-9].[0-9].*$ ]]; then
            echo "Invalid version!"
            exit 1
          fi

      - name: Tag and release
        uses: avakar/tag-and-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
