name: Snap Testing

on:
  pull_request:
    branches: [ main ]
  # allow manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build and upload snap
        id: build
        # uses: canonical/edgex-snap-testing/build@v2
        uses: MonicaisHer/edgex-snap-testing/build@security-off-config-option
    outputs:
      snap: ${{steps.build.outputs.snap}}

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download and test snap
        # uses: canonical/edgex-snap-testing/test@v2
        uses: MonicaisHer/edgex-snap-testing/test@security-off-config-option
        with:
          name: ekuiper
          snap: ${{needs.build.outputs.snap}}